### ISSUE TITLE
Platform dependent commands

### ISSUE THREAD

**Issue by sshankjha** [OODD-Mozilla/ToolRepository#13]
When I try to run the code 'gitApi.js', following error is thrown:

_'rm' is not recognized as an internal or external command,_
operable program or batch file.
child_process.js:526
    throw err;
    ^

Error: Command failed: rm -r ./tmp
_'rm' is not recognized as an internal or external command,_
operable program or batch file.

    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at C:\Users\shash\WebstormProjects\OODD\ToolRepository\gitApi.js:123:4
    at Request._callback (C:\Users\shash\WebstormProjects\OODD\ToolRepository\gitApi.js:44:4)
    at Request.self.callback (C:\Users\shash\WebstormProjects\OODD\ToolRepository\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\shash\WebstormProjects\OODD\ToolRepository\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)

This error is caused due to following line:
		_execSync("rm -r ./tmp");_

There is no 'rm' command in windows. So is this the right way of deleting the folder? Shouldn't we use node libraries rather than platform dependent command to delete the folder?

**Comment by Nikhila-B** [comment]
https://github.com/isaacs/rimraf -'rm - rf' equivalent for node 
reference to use to remove platform dependency - will address soon

**Comment by sshankjha** [comment]
How about using this one:

https://www.npmjs.com/package/fs-extra

1. They built it because: 'I got tired of including mkdirp, **rimraf**, and ncp in most of my projects.'
2. We are already using 'fs'.  All methods in fs are unmodified and attached to fs-extra.

So rather than having two separate libraries for reading and deleting folder/files, better to use one. Let me know what you think.

**Comment by Nikhila-B** [comment]
This should also work! Will use this

**Comment by Nikhila-B** [comment]
addressed - using fs
